version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.docker/config.json:/config.json
    command: --interval 10 --label-enable

  clock:
    image: docker.pkg.github.com/clabroche/docker-registry/clock:latest
    hostname: clock
    restart: always
    environment:
      PORT: 8787
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    expose:
      - 8787
    ports:
      - 8787:8787
